install.packages("tidyverse", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("survival", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("FSA", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("foreach", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("doParallel", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("dplyr", repos = "https://cloud.r-project.org/", dependencies=TRUE)
